-d D:\Backup1\AI Hardware Accelerator\GoAI\GoWin_Project\GoWin_DK_Start\led_flash\GoWIN_FPGA_LED_Flash\impl\gwsynthesis\led_flash.vg
-p GW5A-25A-UBGA324-2
-pn GW5A-LV25UG324C2/I1
-cst D:\Backup1\AI Hardware Accelerator\GoAI\GoWin_Project\GoWin_DK_Start\led_flash\GoWIN_FPGA_LED_Flash\src\led_flash.cst
-cfg D:\Backup1\AI Hardware Accelerator\GoAI\GoWin_Project\GoWin_DK_Start\led_flash\GoWIN_FPGA_LED_Flash\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
